export enum OpportunityStage {
    QUALIFICATION = 'QUALIFICATION',
    NEEDS_ANALYSIS = 'NEEDS_ANALYSIS',
    PROPOSAL = 'PROPOSAL',
    NEGOTIATION = 'NEGOTIATION',
    CLOSED_WON = 'CLOSED_WON',
    CLOSED_LOST = 'CLOSED_LOST',
  }