export enum Permissions {
  // Auth & User Management
  VIEW_USERS = 'VIEW_USERS',
  VIEW_SINGLE_USER = 'VIEW_SINGLE_USER',
  CREATE_USER = 'CREATE_USER',
  DELETE_USER = 'DELETE_USER',
  ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER',

  // Role Management
  VIEW_ROLE = 'VIEW_ROLE',
  VIEW_SINGLE_ROLE = 'VIEW_SINGLE_ROLE',
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  // Campaign Management
  VIEW_CAMPAIGNS_ALL = 'VIEW_CAMPAIGNS_ALL',
  VIEW_CAMPAIGNS_SELF = 'VIEW_CAMPAIGNS_SELF',
  VIEW_SINGLE_CAMPAIGN = 'VIEW_SINGLE_CAMPAIGN',
  CREATE_CAMPAIGN = 'CREATE_CAMPAIGN',
  UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN',
  DELETE_CAMPAIGN = 'DELETE_CAMPAIGN',
  MANAGE_CAMPAIGN_LEADS = 'MANAGE_CAMPAIGN_LEADS',
  VIEW_CAMPAIGN_LEADS = 'VIEW_CAMPAIGN_LEADS',
  VIEW_CAMPAIGN_OPPORTUNITIES = 'VIEW_CAMPAIGN_OPPORTUNITIES',

  // Lead Management
  VIEW_LEADS_ALL = 'VIEW_LEADS_ALL',
  VIEW_LEADS_SELF = 'VIEW_LEADS_SELF',
  VIEW_SINGLE_LEAD = 'VIEW_SINGLE_LEAD',
  CREATE_LEAD = 'CREATE_LEAD',
  UPDATE_LEAD = 'UPDATE_LEAD',
  DELETE_LEAD = 'DELETE_LEAD',
  VIEW_LEAD_REMINDERS = 'VIEW_LEAD_REMINDERS',

  // Opportunity Management
  VIEW_OPPORTUNITIES_ALL = 'VIEW_OPPORTUNITIES_ALL',
  VIEW_OPPORTUNITIES_SELF = 'VIEW_OPPORTUNITIES_SELF',
  VIEW_SINGLE_OPPORTUNITY = 'VIEW_SINGLE_OPPORTUNITY',
  CREATE_OPPORTUNITY = 'CREATE_OPPORTUNITY',
  UPDATE_OPPORTUNITY = 'UPDATE_OPPORTUNITY',
  DELETE_OPPORTUNITY = 'DELETE_OPPORTUNITY',
  VIEW_LEAD_OPPORTUNITIES = 'VIEW_LEAD_OPPORTUNITIES',

  // Interaction Management
  VIEW_INTERACTIONS = 'VIEW_INTERACTIONS',
  VIEW_SINGLE_INTERACTION = 'VIEW_SINGLE_INTERACTION',
  CREATE_INTERACTION = 'CREATE_INTERACTION',
  UPDATE_INTERACTION = 'UPDATE_INTERACTION',
  DELETE_INTERACTION = 'DELETE_INTERACTION',
  VIEW_LEAD_INTERACTIONS = 'VIEW_LEAD_INTERACTIONS',

  // Task Management
  VIEW_TASKS = 'VIEW_TASKS',
  VIEW_SINGLE_TASK = 'VIEW_SINGLE_TASK',
  CREATE_TASK = 'CREATE_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  DELETE_TASK = 'DELETE_TASK',

  // Reminder Management
  VIEW_REMINDERS_ALL = 'VIEW_REMINDERS_ALL',
  VIEW_REMINDERS_SELF = 'VIEW_REMINDERS_SELF',
  VIEW_SINGLE_REMINDER = 'VIEW_SINGLE_REMINDER',
  CREATE_REMINDER = 'CREATE_REMINDER',
  UPDATE_REMINDER = 'UPDATE_REMINDER',
  DELETE_REMINDER = 'DELETE_REMINDER',

  // Optin Form Management
  VIEW_OPTIN_FORMS_ALL = 'VIEW_OPTIN_FORMS_ALL',
  VIEW_OPTIN_FORMS_SELF = 'VIEW_OPTIN_FORMS_SELF',
  CREATE_OPTIN_FORM = 'CREATE_OPTIN_FORM',
  UPDATE_OPTIN_FORM = 'UPDATE_OPTIN_FORM',
  DELETE_OPTIN_FORM = 'DELETE_OPTIN_FORM',

}
